# Generated by Django 5.2.2 on 2025-09-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_full_name_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('tenant_admin', 'Tenant_admin'), ('customer', 'Customer')], max_length=20),
        ),
    ]
