# Generated by Django 5.2.2 on 2025-07-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(choices=[('online', 'Online'), ('walk_in', 'Walk-In')], default='online', max_length=20),
        ),
    ]
