# Generated by Django 5.2.2 on 2025-07-18 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('mpesa_consumer_key', models.CharField(max_length=200)),
                ('mpesa_consumer_secret', models.CharField(max_length=200)),
                ('mpesa_shortcode', models.CharField(max_length=50)),
                ('mpesa_passkey', models.CharField(max_length=300)),
                ('mpesa_callback_url', models.URLField(max_length=100)),
                ('mpesa_env', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('carwash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tenant.carwash')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('carwash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tenant.carwash')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tenant.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='carwash',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carwashes', to='tenant.tenant'),
        ),
    ]
